version: '3.7'
services:

  jaeger-worm:
    build: ./worker
    container_name: jaeger-worm
    networks:
    - core
    - postgres
    env_file:
    - .env

  hermes-jaeger-worm:
    build: ./hermes
    container_name: hermes-jaeger-worm
    networks:
    - core

networks:
  core:
    name: core
  postgres:
    name: postgres